server:
  port: 8082
spring:
  application:
    name: service-provider # 应用名称，注册到eureka后的服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/mp
    username: root
    password: root

mybatis:
  type-aliases-package: com.huihex.pojo
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
